packages:
 - 'packages/*'
 - 'packages/cli/*'
 - 'packages/runtime/*'
 - 'packages/generator/*'
 - 'packages/generator/generators/*'
 - 'packages/generator/plugins/*'
 - 'packages/review/*'
 - 'packages/server/*'
 - 'packages/builder/*'
 - 'packages/solutions/*'
 - 'packages/toolkit/*'
 - 'packages/toolkit/compiler/*'
 - 'scripts/*'
 - 'tests'
 - 'tests/integration/**/*'
 - 'website'
 - '!packages/solutions/module-tools-v2'
