packages:
 - 'examples/*'
 - 'packages/*'
 - 'packages/cli/*'
 - 'packages/generator/*'
 - 'packages/generator/generators/*'
 - 'packages/generator/plugins/*'
 - 'packages/review/*'
 - 'packages/server/*'
 - 'packages/solutions/*'
 - 'packages/toolkit/*'
 - 'packages/toolkit/compiler/*'
 - 'tests'
 - 'tests/integration/**/*'
