module.exports = {
  collectCoverage: false,
  coverageDirectory: 'coverage',
  coverageProvider: 'v8',
  preset: 'jest-puppeteer',
  rootDir: __dirname,
  setupFilesAfterEnv: ['./utils/jest.setup.js'],
  testMatch: ['<rootDir>/integration/**/*.(spec|test).[tj]s?(x)'],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/api-service-koa/api/',
    '/api-service-koa/dist',
    '/api/tests',
    'integration/alias-set/',
    'integration/app-document/',
    'integration/builder-rspack/',
    'integration/builder-rspack-with-ssr/',
    'integration/css/',
    'integration/css-modules/',
    'integration/mwa-app/',
    'integration/runtime/',
    'integration/ssr/',
    'integration/custom-render/',
    'integration/bff-koa/',
    'integration/dev-server/',
    'integration/routes/',
    'integration/doc/',
    'integration/server-hook/',
  ],
  transform: {
    '^.+.tsx?$': 'ts-jest',
  },
  testEnvironment: './utils/puppeteer_environment.js',
  globalSetup: './utils/setup.js',
  globalTeardown: './utils/teardown.js',
  testSequencer: './utils/custom-sequencer.js',
};
