declare module 'acorn-class-fields';
declare module 'find-node-modules';
declare module '@svgr/core';
declare module '@svgr/plugin-jsx';
declare module 'launch-editor';
declare module 'merge-source-map';
declare module 'convert-source-map';
declare module 'node-fetch';
declare module '@babel/generator';
