// Server component - no 'server-only' import needed
import { Suspense, lazy } from 'react';

// Dynamic imports for Module Federation remote components
// These use lazy() which defers loading until render time
// @ts-expect-error - Types will be generated by Module Federation
const Counter = lazy(() => import('rsc_ssr_remote/Counter'));
// @ts-expect-error - Types will be generated by Module Federation
const DynamicMessage = lazy(() => import('rsc_ssr_remote/DynamicMessage'));

export default function App() {
  return (
    <div
      className="host-root"
      style={{ padding: '20px', fontFamily: 'system-ui' }}
    >
      <h1>SSR Host Application</h1>
      <p>This host app consumes remote components from rsc-ssr-mf</p>

      <section
        className="remote-section"
        style={{ marginTop: '20px', padding: '10px', border: '1px solid #ccc' }}
      >
        <h2>Remote Counter Component (from SSR remote)</h2>
        <Suspense fallback={<div className="loading">Loading Counter...</div>}>
          <Counter />
        </Suspense>
      </section>

      <section
        className="remote-section"
        style={{ marginTop: '20px', padding: '10px', border: '1px solid #ccc' }}
      >
        <h2>Remote Dynamic Message (from SSR remote)</h2>
        <Suspense fallback={<div className="loading">Loading Message...</div>}>
          <DynamicMessage />
        </Suspense>
      </section>
    </div>
  );
}
