'use client';

import { Suspense, lazy } from 'react';
import './App.css';

// Dynamic imports for Module Federation remote components from rsc-ssr-mf
// @ts-expect-error - Types will be generated by Module Federation
const Counter = lazy(() => import('rsc_ssr_remote/Counter').then(m => ({ default: m.Counter || m.default })));
// @ts-expect-error - Types will be generated by Module Federation
const DynamicMessage = lazy(() => import('rsc_ssr_remote/DynamicMessage').then(m => ({ default: m.DynamicMessage || m.default })));

export default function ClientRoot() {
  return (
    <div className="host-root">
      <h1>SSR Host Application</h1>
      <p>This SSR host app consumes remote components from rsc-ssr-mf</p>

      <section className="remote-section">
        <h2>Remote Counter Component (from SSR remote)</h2>
        <Suspense fallback={<div className="loading">Loading Counter...</div>}>
          <Counter />
        </Suspense>
      </section>

      <section className="remote-section">
        <h2>Remote Dynamic Message (from SSR remote)</h2>
        <Suspense fallback={<div className="loading">Loading Message...</div>}>
          <DynamicMessage />
        </Suspense>
      </section>
    </div>
  );
}
