import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Copies a documentation site's build output into a package as `docs/`, so
// every project gets version-matched offline docs for AI coding agents (see the
// AGENTS.md generated by @modern-js/create).
//
// The source is the docs site's *build output*, not the MDX sources. Rspress
// renders components and inlines shared fragments at build time, so the build
// output is self-contained Markdown an agent can read directly — the MDX
// sources are not: a quarter of the pages get their actual content from
// components whose data never ships with the package.
//
// Frameworks built on Modern.js (EdenX, PIA) ship their own docs the same way,
// so this is exposed as a function and a `modern-bundle-docs` bin instead of
// being hardcoded to Modern.js's own paths.
const __dirname = path.dirname(fileURLToPath(import.meta.url));

// The docs site also emits HTML, assets and translated trees; agents only need
// one language's Markdown plus llms.txt as an index. llms-full.txt is a
// concatenation of the same pages, so it would only duplicate what we ship.
const DEFAULT_INDEX_FILE = 'llms.txt';
const DEFAULT_EXCLUDED_DIRS = ['zh'];

/**
 * @param {object} options
 * @param {string} options.source docs site build output (e.g. `doc_build`)
 * @param {string} options.target directory to write the bundle to
 * @param {string} [options.indexFile] index file to ship alongside the pages
 * @param {string[]} [options.excludedDirs] top-level directories to skip
 * @returns {number} files copied, or 0 when the source is absent
 */
export function bundleDocs({
  source,
  target,
  indexFile = DEFAULT_INDEX_FILE,
  excludedDirs = DEFAULT_EXCLUDED_DIRS,
}) {
  if (!fs.existsSync(source)) {
    // Not fatal: the docs site is excluded from most builds, and blocking every
    // package build on it would slow day-to-day work down for no reason. The
    // release path builds the docs first, and check-doc-bundle.mjs fails loudly
    // if a tarball ends up without them.
    console.warn(`[bundle-docs] docs build output not found: ${source}`);
    console.warn(
      '[bundle-docs] skipping the bundled docs — build the docs site first if you need them',
    );
    return 0;
  }

  fs.rmSync(target, { recursive: true, force: true });

  const isBundled = rel =>
    rel === indexFile ||
    (rel.endsWith('.md') &&
      !excludedDirs.some(dir => rel.startsWith(`${dir}${path.sep}`)));

  let count = 0;
  for (const entry of fs.readdirSync(source, {
    recursive: true,
    withFileTypes: true,
  })) {
    if (!entry.isFile()) {
      continue;
    }
    const from = path.join(entry.parentPath ?? entry.path, entry.name);
    const rel = path.relative(source, from);
    if (!isBundled(rel)) {
      continue;
    }
    const to = path.join(target, rel);
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
    count++;
  }

  if (count === 0) {
    throw new Error(`[bundle-docs] no files copied from ${source}`);
  }
  return count;
}

function parseArgs(argv) {
  const options = {};
  for (let i = 0; i < argv.length; i += 2) {
    const key = argv[i]?.replace(/^--/, '');
    if (key && argv[i + 1]) {
      options[key] = argv[i + 1];
    }
  }
  return options;
}

// CLI: `modern-bundle-docs --source <doc_build> --target <pkg>/docs`
// Both default to Modern.js's own layout when omitted.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const pkgRoot = path.resolve(__dirname, '..');
  const args = parseArgs(process.argv.slice(2));
  const source = args.source
    ? path.resolve(process.cwd(), args.source)
    : path.resolve(pkgRoot, '../../document/doc_build');
  const target = args.target
    ? path.resolve(process.cwd(), args.target)
    : path.resolve(pkgRoot, 'docs');

  try {
    const count = bundleDocs({ source, target, indexFile: args.index });
    if (count > 0) {
      console.log(`[bundle-docs] bundled ${count} doc files into docs`);
    }
  } catch (error) {
    console.error(error.message);
    process.exit(1);
  }
}
