name: "✨ 新功能建议"
description: 给 Modern.js 提交新功能建议
title: "[RFC]: "
labels: ["rfc"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间报告提交新功能建议！在提交功能需求前，请注意：

        - 确认这是一个通用功能，并且无法通过现有的 API 实现。
        - 确认你搜索过 [历史 issue](https://github.com/modern-js-dev/modern.js/issues)，并且没有发现同样的需求。
        - 可以先到 [Discussions 讨论区](https://github.com/modern-js-dev/modern.js/discussions) 发帖，讨论一下需求是否合理。

  - type: textarea
    id: description
    attributes:
      label: 这个功能解决了什么问题？
      description: 请清晰地描述此功能的使用场景。
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: 你期望的 API 是什么样子的？
      description: 描述一下这个新功能的 API，并提供简要的示例。
    validations:
      required: true
