'use client';

import { Suspense, lazy } from 'react';
import './App.css';

// Dynamic imports for Module Federation remote components
// @ts-expect-error - Types will be generated by Module Federation
const Counter = lazy(() => import('rsc_csr_remote/CounterClient').then(m => ({ default: m.Counter || m.default })));
// @ts-expect-error - Types will be generated by Module Federation
const DynamicMessage = lazy(() => import('rsc_csr_remote/DynamicMessageClient'));
// @ts-expect-error - Types will be generated by Module Federation
const Suspended = lazy(() => import('rsc_csr_remote/SuspendedClient'));

export default function ClientRoot() {
  return (
    <div className="host-root">
      <h1>Host Application</h1>
      <p>This host app consumes remote components from rsc-csr-mf</p>

      <section className="remote-section">
        <h2>Remote Counter Component</h2>
        <Suspense fallback={<div className="loading">Loading Counter...</div>}>
          <Counter />
        </Suspense>
      </section>

      <section className="remote-section">
        <h2>Remote Dynamic Message</h2>
        <Suspense fallback={<div className="loading">Loading Message...</div>}>
          <DynamicMessage />
        </Suspense>
      </section>

      <section className="remote-section">
        <h2>Remote Suspended Component</h2>
        <Suspense fallback={<div className="loading">Loading Suspended...</div>}>
          <Suspended />
        </Suspense>
      </section>
    </div>
  );
}
