// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  backdrop: string;
  container: string;
  frame: string;
  loading: string;
  rotate: string;
}
export const cssExports: CssExports;
export default cssExports;
