/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  quickStartSidebar: [{ type: 'autogenerated', dirName: 'start' }],
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  apisAppSidebar: [{ type: 'autogenerated', dirName: 'apis/app' }],
  apisModuleSidebar: [{ type: 'autogenerated', dirName: 'apis/module' }],
  apisMonorepoSidebar: [{ type: 'autogenerated', dirName: 'apis/monorepo' }],
  apisGeneratorSidebar: [{ type: 'autogenerated', dirName: 'apis/generator' }],
  apisRuntimeSidebar: [{ type: 'autogenerated', dirName: 'apis/runtime' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
