export const enum ErrorCode {
  CONFIG_NOT_EXIT = 'CONFIG_NOT_EXIT',
  CONFIG_TRANSFORM_FAILED = 'CONFIG_TRANSFORM_FAILED',
  CONFIG_TRANSFORM_WARN = 'CONFIG_TRANSFORM_WARN',
  NODE_RESOLVE_FAILED = 'NODE_RESOLVE_FAILED',
  ESBUILD_ERROR = 'ESBUILD_ERROR',
  ESBUILD_WARN = 'ESBUILD_WARN',
  VALIDATE_CONFIG_FAILED = 'VALIDATE_CONFIG_FAILED',
  RESOLVE_OUT_OF_PLUGIN = 'RESOLVE_OUT_OF_PLUGIN',
  PLUGIN_INTERNAL_ERROR = 'PLUGIN_INTERNAL_ERROR',
}
