/* eslint-disable */
// This file is auto-generated by Modern.js. Do not edit manually.

import {
  createMemoryHistory,
  createRootRouteWithContext,
  createRoute,
  createRouter,
  notFound,
  redirect,
} from '@modern-js/plugin-tanstack/runtime';

type ModernRouterContext = {
  request?: Request;
  requestContext?: unknown;
};

function isResponse(value: unknown): value is Response {
  return (
    value != null &&
    typeof value === 'object' &&
    typeof (value as any).status === 'number' &&
    typeof (value as any).headers === 'object'
  );
}

const redirectStatusCodes = new Set([301, 302, 303, 307, 308]);
function isRedirectResponse(res: Response) {
  return redirectStatusCodes.has(res.status);
}

function throwTanstackRedirect(location: string) {
  const target = location || '/';
  try {
    void new URL(target);
    throw redirect({ href: target });
  } catch {
    throw redirect({ to: target });
  }
}

function mapParamsForModernLoader(params: Record<string, string>, hasSplat: boolean) {
  if (!hasSplat) {
    return params;
  }

  const { _splat, ...rest } = params as any;
  if (typeof _splat !== 'undefined') {
    return { ...rest, '*': _splat };
  }
  return rest;
}

function createRouteStaticData(opts: {
  modernRouteId?: string;
  modernRouteLoader?: unknown;
}) {
  const staticData: Record<string, unknown> = {};

  if (opts.modernRouteId) {
    staticData.modernRouteId = opts.modernRouteId;
  }

  if (opts.modernRouteLoader) {
    staticData.modernRouteLoader = opts.modernRouteLoader;
  }

  return Object.keys(staticData).length > 0 ? staticData : undefined;
}

function modernLoaderToTanstack<TLoader extends (args: any) => any>(
  opts: { hasSplat: boolean },
  modernLoader: TLoader,
) {
  type LoaderResult = Awaited<ReturnType<TLoader>>;

  return async (ctx: any): Promise<LoaderResult> => {
    try {
      const signal: AbortSignal =
        ctx?.abortController?.signal ||
        ctx?.signal ||
        new AbortController().signal;
      const baseRequest: Request | undefined =
        ctx?.context?.request instanceof Request ? ctx.context.request : undefined;

      const href =
        typeof ctx?.location === 'string'
          ? ctx.location
          : ctx?.location?.publicHref ||
            ctx?.location?.href ||
            ctx?.location?.url?.href ||
            '';

      const request = baseRequest
        ? new Request(baseRequest, { signal })
        : new Request(href, { signal });

      const params = mapParamsForModernLoader(ctx?.params || {}, opts.hasSplat);

      const result = await (modernLoader as any)({
        request,
        params,
        context: ctx?.context?.requestContext,
      });

      if (isResponse(result)) {
        if (isRedirectResponse(result)) {
          const location = result.headers.get('Location') || '/';
          throwTanstackRedirect(location);
        }
        if (result.status === 404) {
          throw notFound();
        }
      }

      return result as LoaderResult;
    } catch (err) {
      if (isResponse(err)) {
        if (isRedirectResponse(err)) {
          const location = err.headers.get('Location') || '/';
          throwTanstackRedirect(location);
        }
        if (err.status === 404) {
          throw notFound();
        }
      }
      throw err;
    }
  };
}

import loader_0 from "../../stream/routes/layout.loader";
import { loader as loader_1 } from "../../stream/routes/page.data";
import { loader as loader_2 } from "../../stream/routes/optional/[id$]/page.data";
import { loader as loader_3 } from "../../stream/routes/redirect/page.data";
import { loader as loader_4 } from "../../stream/routes/user/[id]/page.data";

export const rootRoute = createRootRouteWithContext<ModernRouterContext>()({
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_0),
  staticData: createRouteStaticData({
    modernRouteId: "stream_layout",
    modernRouteLoader: loader_0,
  }),
});

const route_stream_page = createRoute({
  getParentRoute: () => rootRoute,
  path: "/",
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_1),
  staticData: createRouteStaticData({
    modernRouteId: "stream_page",
    modernRouteLoader: loader_1,
  }),
});

const route_stream_optional__id$__page = createRoute({
  getParentRoute: () => rootRoute,
  path: "optional/{-$id}",
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_2),
  staticData: createRouteStaticData({
    modernRouteId: "stream_optional/(id$)/page",
    modernRouteLoader: loader_2,
  }),
});

const route_stream_redirect_page = createRoute({
  getParentRoute: () => rootRoute,
  path: "redirect",
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_3),
  staticData: createRouteStaticData({
    modernRouteId: "stream_redirect/page",
    modernRouteLoader: loader_3,
  }),
});

const route_stream_user__id__page = createRoute({
  getParentRoute: () => rootRoute,
  path: "user/$id",
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_4),
  staticData: createRouteStaticData({
    modernRouteId: "stream_user/(id)/page",
    modernRouteLoader: loader_4,
  }),
});

export const routeTree = rootRoute.addChildren([route_stream_page, route_stream_optional__id$__page, route_stream_redirect_page, route_stream_user__id__page]);

export const router = createRouter({
  routeTree,
  history: createMemoryHistory({
    initialEntries: ['/'],
  }),
  context: {} as ModernRouterContext,
});
