export enum STATUS {
  INITIAL = 'INITIAL',
  BEFORE_INIT_PLUGINS = 'BEFORE_INIT_PLUGINS',
  AFTER_INIT_PLUGINS = 'AFTER_INIT_PLUGINS',
  BEFORE_MODIFY_BUILDER_CONFIG = 'BEFORE_MODIFY_BUILDER_CONFIG',
  AFTER_MODIFY_BUILDER_CONFIG = 'AFTER_MODIFY_BUILDER_CONFIG',
  BEFORE_MODIFY_WEBPACK_CHAIN = 'BEFORE_MODIFY_WEBPACK_CHAIN',
  AFTER_MODIFY_WEBPACK_CHAIN = 'AFTER_MODIFY_WEBPACK_CHAIN',
  BEFORE_MODIFY_WEBPACK_CONFIG = 'BEFORE_MODIFY_WEBPACK_CONFIG',
  AFTER_MODIFY_WEBPACK_CONFIG = 'AFTER_MODIFY_WEBPACK_CONFIG',
}

export const DEFAULT_PORT = 8080;

export const DEFAULT_DIST_DIR = 'dist';

export const DEFAULT_DATA_URL_SIZE = 10000;

export const IMAGE_EXTENSIONS = [
  'png',
  'jpg',
  'jpeg',
  'gif',
  'bmp',
  'webp',
  'ico',
  'apng',
  'avif',
  'tiff',
];
