export enum STATUS {
  INITIAL = 'INITIAL',
  BEFORE_INIT_PLUGINS = 'BEFORE_INIT_PLUGINS',
  AFTER_INIT_PLUGINS = 'AFTER_INIT_PLUGINS',
  BEFORE_MODIFY_BUILDER_CONFIG = 'BEFORE_MODIFY_BUILDER_CONFIG',
  AFTER_MODIFY_BUILDER_CONFIG = 'AFTER_MODIFY_BUILDER_CONFIG',
  BEFORE_MODIFY_WEBPACK_CHAIN = 'BEFORE_MODIFY_WEBPACK_CHAIN',
  AFTER_MODIFY_WEBPACK_CHAIN = 'AFTER_MODIFY_WEBPACK_CHAIN',
  BEFORE_MODIFY_WEBPACK_CONFIG = 'BEFORE_MODIFY_WEBPACK_CONFIG',
  AFTER_MODIFY_WEBPACK_CONFIG = 'AFTER_MODIFY_WEBPACK_CONFIG',
}
