#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# skip husky in CI
# https://typicode.github.io/husky/guide.html#with-env-variables
[ -n "$CI" ] && exit 0

# avoid conflicts in pnpm lock
# https://7tonshark.com/posts/avoid-conflicts-in-pnpm-lock/
git config merge.ours.driver true
