name: Build DevTools Website

on:
  push:
    branches: [main, dev/modernjs-devtools]
    paths:
      - 'packages/devtools/client/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-devtools-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.ref_name }}-
            turbo-

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: pnpm install

      - name: Build Website
        run: pnpm --filter @modern-js/devtools-client run build
        env:
          ASSET_PREFIX: https://web-infra-dev.github.io/devtools/${{ steps.vars.outputs.sha_short }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          repository-name: web-infra-dev/web-infra-dev.github.io
          branch: main
          folder: packages/devtools/client/dist
          token: ${{ secrets.MODERN_DEPLOY_TOKEN }}
          target-folder: devtools/${{ steps.vars.outputs.sha_short }}
          git-config-name: gh-pages-bot
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          clean: true
