name: Cypress Test

concurrency:
  group: macos-cypress-test-${{ github.head_ref }}
  cancel-in-progress: true

# Controls when the action will run.
on:
  # Triggers unit test on push events for the main branch to collect unit test coverage
  push:
    branches: [main]


jobs:
  e2e-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.14.0]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: wireit cache
      uses: google/wireit@setup-github-actions-caching/v1
    - uses: pnpm/action-setup@v2.0.1
      name: Install pnpm
      id: pnpm-install
      with:
        version: 6.32.17
        run_install: false

    - name: Install Dependencies
      run: pnpm install --ignore-scripts --frozen-lockfile

    - name: Install cypress
      run: npx cypress install

    - name: Prepare
      if: ${{steps.docs-change.outputs.DOCS_CHANGE != 'docs only change'}}
      run: pnpm run prepare --filter ./packages

    - name: Run cypress test
      uses: cypress-io/github-action@v4
      with:
        install: false
        start: node scripts/dev-project.js
        wait-on: 'http://localhost:3001,http://localhost:3002,http://localhost:3003/index.js'
        wait-on-timeout: 600
        working-directory: tests
        spec: cypress/e2e/**/*.cy.js
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        # Recommended: pass the GitHub token lets this action correctly
        # determine the unique run id necessary to re-run the checks
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
