name: Integration Test(Linux)

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the main branch
  push:
    branches: [main, update-rspack-**]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  integration-test-linux:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest] # ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 25

      - name: Install Pnpm
        run: corepack enable

      - name: Check docs only change
        run: echo ::set-output name=DOCS_CHANGE::$(node ./scripts/skipDocsChange.js echo 'not-docs-only-change')
        id: docs-change

      - run: echo ${{steps.docs-change.outputs.DOCS_CHANGE}}

      - name: Setup Node.js ${{ matrix.node-version }}
        if: ${{steps.docs-change.outputs.DOCS_CHANGE != 'docs only change'}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.ref_name }}-
            turbo-

      - name: Install Dependencies
        if: ${{steps.docs-change.outputs.DOCS_CHANGE != 'docs only change'}}
        run: pnpm install --ignore-scripts --frozen-lockfile

      - name: Prepare
        if: ${{steps.docs-change.outputs.DOCS_CHANGE != 'docs only change'}}
        run: pnpm run prepare

      - name: Install Puppeteer
        if: ${{steps.docs-change.outputs.DOCS_CHANGE != 'docs only change'}}
        run: cd ./tests/node_modules/puppeteer && npm run postinstall && cd ../..

      - name: Test
        if: ${{steps.docs-change.outputs.DOCS_CHANGE != 'docs only change'}}
        run: cd ./tests && pnpm run test
