name: Label Issues

on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Label issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REPO_SCOPED_TOKEN }}
          script: |
            const title = context.payload.issue.title

            if (title.startsWith('Benchmark')) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['benchmark']
              })
            }
