name: Module Tools Test (Windows)

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the main branch
  push:
    branches: [main, dev/**]

  merge_group:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  module-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Pnpm
        run: corepack enable

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'pnpm'

      - name: Nx Cache
        id: nx-cache
        uses: actions/cache@v3
        with:
          path: .nx/cache
          key: nx-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            nx-${{ github.ref_name }}-
            nx-

      - name: Install Dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile

      - name: Prepare
        run: pnpm run prepare

      - name: Install Puppeteer
        run: cd ./tests/node_modules/puppeteer && npm run postinstall && cd ../..

      - name: Test
        run: cd ./tests && pnpm run test:module-tools
