name: E2E Test (Garfish)

on:
  push:
    branches: [v2, renovate/v2-rsbuild]

  workflow_dispatch:

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 1

      - name: Nx Cache
        id: nx-cache
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
        with:
          path: .nx/cache
          key: nx-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            nx-${{ github.ref_name }}-
            nx-

      - name: Install Pnpm
        run: npm i -g --force corepack && corepack enable

      - name: Setup Node.js 18
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: "18"
          cache: 'pnpm'

      - name: Install Dependencies
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: pnpm install

      - name: Install playwright
        run: node packages/toolkit/e2e/node_modules/@playwright/test/cli.js install chromium

      - name: Test
        run: cd ./tests/e2e/garfish && pnpm run test
