name: E2E Test (Garfish)

on:
  push:
    branches: [main, feat-update-rsbuild-*]

  workflow_dispatch:

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Nx Cache
        id: nx-cache
        uses: actions/cache@v3
        with:
          path: .nx/cache
          key: nx-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            nx-${{ github.ref_name }}-
            nx-

      - name: Install Pnpm
        run: corepack enable

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Install playwright
        run: node packages/toolkit/e2e/node_modules/@playwright/test/cli.js install

      - name: Test
        run: cd ./tests/e2e/garfish && pnpm run test
